export const profileData = {
    first_name: 'Иван',
    second_name: 'Иванов',
    display_name: 'Иван',
    login: 'ivan',
    email: 'ivan@ivanovo.ru',
    phone: '+7 (987) 654 32 10',
    avatar: null,
    oldPassword: 'oldPassword',
    newPassword: '',
    disabled: true,
}


export const loginFormData = {
    title: 'Вход',
    submit: 'Авторизоваться',
    link: 'Нет аккаунта?',
    items: [
        {
            id: 'login',
            name: 'login',
            label: 'Логин',
            type: 'text',
            error: null,
            value: '',
        },
        {
            id: 'password',
            name: 'password',
            label: 'Пароль',
            type: 'password',
            error: null, //false
            value: '',
        },
    ]
}

export const registrationFormData = {
    title: 'Регистрация',
    submit: 'Зарегистрироваться',
    link: 'Войти',
    items: [
        {
            label: 'Почта',
            id: 'email',
            name: 'email',
            type: 'text',
            error: null, //false
            value: '',
        },
        {
            label: 'Логин',
            id: 'login',
            name: 'login',
            type: 'text',
            error: null, //false
            value: '',
        },
        {
            label: 'Имя',
            id: 'first_name',
            name: 'first_name',
            type: 'text',
            error: null, //false
            value: '',
        },
        {
            label: 'Фамилия',
            id: 'second_name',
            name: 'second_name',
            type: 'text',
            error: null, //false
            value: '',
        },
        {
            label: 'Телефон',
            id: 'phone',
            name: 'phone',
            type: 'text',
            error: null, //false
            value: '',
        },
        {
            label: 'Пароль',
            id: 'password',
            name: 'password',
            type: 'password',
            error: null, //false
            value: '',
        },
        {
            label: 'Пароль(ещё раз)',
            id: 'password_repeat',
            name: 'password_repeat',
            type: 'password',
            error: null, //false
            value: '',
        },
    ]
}

export const chatList = [
    {
        id: '1',
        date: '01.01.2025',
        time: '11:42',
        title: 'Андрей',
        message: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam, sed.',
        unread: 4,
        lastMe: false,
        active: false,
    },
    {
        id: '2',
        date: '31.12.2024',
        time: '23:15',
        title: 'Мария',
        message: 'С Новым годом! 🎉',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '3',
        date: '30.12.2024',
        time: '14:20',
        title: 'Сергей',
        message: 'Когда сможем встретиться по проекту?',
        unread: 2,
        lastMe: false,
        active: false,
    },
    {
        id: '4',
        date: '29.12.2024',
        time: '09:05',
        title: 'Ольга',
        message: 'Отправила документы на проверку',
        unread: 1,
        lastMe: false,
        active: false,
    },
    {
        id: '5',
        date: '28.12.2024',
        time: '18:40`',
        title: 'Дмитрий',
        message: 'Да, договорились на завтра в 10:00',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '6',
        date: '27.12.2024',
        time: '16:30',
        title: 'Вадим',
        message: 'Круто!',
        unread: 0,
        lastMe: true,
        active: true,
    },
    {
        id: '7',
        date: '27.12.2024',
        time: '12:10',
        title: 'Алексей',
        message: 'Привет, как дела?',
        unread: 3,
        lastMe: false,
        active: false,
    },
    {
        id: '8',
        date: '26.12.2024',
        time: '20:15',
        title: 'Анна',
        message: 'Отличная была вечеринка!',
        unread: 0,
        lastMe: false,
        active: false,
    },
    {
        id: '9',
        date: '25.12.2024',
        time: '11:00',
        title: 'Иван',
        message: 'С Рождеством!',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '10',
        date: '24.12.2024',
        time: '15:45',
        title: 'Наталья',
        message: 'Завтра работаем до 18:00',
        unread: 5,
        lastMe: false,
        active: false,
    },
    {
        id: '11',
        date: '23.12.2024',
        time: '19:20',
        title: 'Павел',
        message: 'Хорошо, увидимся там',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '12',
        date: '22.12.2024',
        time: '10:30',
        title: 'Светлана',
        message: 'Нужна твоя консультация',
        unread: 1,
        lastMe: false,
        active: false,
    },
    {
        id: '13',
        date: '21.12.2024',
        time: '22:05',
        title: 'Максим',
        message: 'Фильм просто супер!',
        unread: 0,
        lastMe: false,
        active: false,
    },
    {
        id: '14',
        date: '20.12.2024',
        time: '13:50',
        title: 'Виктория',
        message: 'Отправила тебе фото',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '15',
        date: '19.12.2024',
        time: '17:25',
        title: 'Артем',
        message: 'Когда освободишься?',
        unread: 2,
        lastMe: false,
        active: false,
    },
    {
        id: '16',
        date: '18.12.2024',
        time: '09:10',
        title: 'Кирилл',
        message: 'Отчет готов, можно проверять',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '17',
        date: '17.12.2024',
        time: '14:35',
        title: 'Татьяна',
        message: 'Завтра встреча в 15:00',
        unread: 3,
        lastMe: false,
        active: false,
    },
    {
        id: '18',
        date: '16.12.2024',
        time: '11:20',
        title: 'Роман',
        message: 'Скинул тебе ссылку на ресурс',
        unread: 0,
        lastMe: false,
        active: false,
    },
    {
        id: '19',
        date: '15.12.2024',
        time: '19:45',
        title: 'Юлия',
        message: 'Спасибо за подарок!',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '20',
        date: '14.12.2024',
        time: '16:50',
        title: 'Михаил',
        message: 'Когда сможешь подъехать?',
        unread: 1,
        lastMe: false,
        active: false,
    },
    {
        id: '21',
        date: '13.12.2024',
        time: '12:15',
        title: 'Вадим',
        message: 'Документы подписаны',
        unread: 0,
        lastMe: false,
        active: false,
    },
    {
        id: '22',
        date: '12.12.2024',
        time: '20:30',
        title: 'Константин',
        message: 'Отлично провели время!',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '23',
        date: '11.12.2024',
        time: '10:05',
        title: 'Алиса',
        message: 'Нужна твоя помощь с настройкой',
        unread: 4,
        lastMe: false,
        active: false,
    },
    {
        id: '24',
        date: '10.12.2024',
        time: '18:20',
        title: 'Владимир',
        message: 'Встречаемся у метро в 19:00',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '25',
        date: '09.12.2024',
        time: '13:40',
        title: 'Оксана',
        message: 'Передала коллеге информацию',
        unread: 0,
        lastMe: false,
        active: false,
    },
    {
        id: '26',
        date: '08.12.2024',
        time: '21:10',
        title: 'Станислав',
        message: 'Посмотри это видео, очень интересно',
        unread: 0,
        lastMe: false,
        active: false,
    },
    {
        id: '27',
        date: '07.12.2024',
        time: '15:55',
        title: 'Галина',
        message: 'Собрание перенесли на пятницу',
        unread: 2,
        lastMe: false,
        active: false,
    },
    {
        id: '28',
        date: '06.12.2024',
        time: '11:25',
        title: 'Борис',
        message: 'Да, все правильно',
        unread: 0,
        lastMe: true,
        active: false,
    },
    {
        id: '29',
        date: '05.12.2024',
        time: '17:45',
        title: 'Валерия',
        message: 'Когда будем делать презентацию?',
        unread: 1,
        lastMe: false,
        active: false,
    },
    {
        id: '30',
        date: '04.12.2024',
        time: '14:00',
        title: 'Николай',
        message: 'Спасибо за рекомендацию!',
        unread: 0,
        lastMe: true,
        active: false,
    }
]
